version: "3"
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
  rsocket-broker:
    image: linuxchina/alibaba-rsocket-broker:1.0.0.M1
    container_name: rsocket-broker
    ports:
      - 9997:9997
      - 9998:9998
      - 9999:9999
  rocketmq-namesrv:
    image: apacherocketmq/rocketmq:4.6.0
    container_name: rocketmq-namesrv
    ports:
      - 9876:9876
    volumes:
      - ~/rocketmq/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv
  rocketmq-broker:
    image: apacherocketmq/rocketmq:4.6.0
    container_name: rocketmq-broker
    links:
      - rocketmq-namesrv
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=192.168.100.7:9876
    volumes:
      - ~/rocketmq/broker/logs:/home/rocketmq/logs
      - ~/rocketmq/broker/store:/home/rocketmq/store
      - ./conf/rocketmq/broker/broker.conf:/opt/rocketmq/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq/conf/broker.conf
  rocketmq-console:
    image: styletang/rocketmq-console-ng
    container_name: rocketmq-console
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=192.168.100.7:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
